# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'photed' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for photed
  pod 'SwiftChart'
  pod 'UIDrawer', :git => 'https://github.com/Que20/UIDrawer.git', :tag => '1.0'

end
